name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      working-directory: .
      run: |
        yarn install
    - name: Lint
      working-directory: .
      run: |
        yarn lint
    - name: Test
      working-directory: .
      run: |
        yarn test
    - name: Build
      working-directory: .
      run: |
        yarn build
